"""
Layer 3 Tool: ollama_client.py
Atomic, deterministic script to communicate with the local Ollama instance.
This tool has ONE job: send a prompt to Ollama, get a response, return it.
"""

import requests
import os
from dotenv import load_dotenv

# Load env config
load_dotenv()

OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434/api/generate")
MODEL_NAME = os.getenv("OLLAMA_MODEL", "llama3.2")


def generate_with_ollama(final_prompt: str) -> str:
    """
    Sends a fully-formed prompt to the local Ollama instance.
    
    Args:
        final_prompt: The complete prompt string (template already applied).
    
    Returns:
        The raw text response from the model.
    
    Raises:
        ConnectionError: If Ollama service is unreachable.
        RuntimeError: If Ollama returns a non-200 HTTP response.
    """
    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": MODEL_NAME,
                "prompt": final_prompt,
                "stream": False
            },
            timeout=120  # LLM inference can take time
        )
    except requests.exceptions.ConnectionError:
        raise ConnectionError(
            f"Cannot reach Ollama at {OLLAMA_URL}. "
            "Please ensure the Ollama service is running locally."
        )
    except requests.exceptions.Timeout:
        raise TimeoutError("Ollama request timed out after 120 seconds.")

    if response.status_code != 200:
        raise RuntimeError(
            f"Ollama returned HTTP {response.status_code}: {response.text}"
        )

    data = response.json()
    result = data.get("response", "").strip()

    if not result:
        return "[No output generated by the model. Please try again with a more detailed input.]"

    return result
